### ISSUE TITLE
When RGL loader is used the blackfin.cfg is ignored

### ISSUE THREAD

**Issue by tommie** [krater/Blackfin-IDA-Pro-Plugin#1]
Adding

``` C
#define CHECK_IORESP 1
```

before including `iocommon.cpp` in `reg.cpp` seems to do the trick. It is used by `apply_config_file` to enable/disable config processing.

**Comment by krater** [comment]
Thanks for the help, but i didn't solved the problem :(

**Comment by krater** [comment]
Okay, it works, thank you. i simply copied the wrong file to the ida
directory.
