### ISSUE TITLE
blackfin adsp bf525

### ISSUE THREAD

**Issue by fmgdias** [krater/Blackfin-IDA-Pro-Plugin#2]
hi krater,

i have a firmware of an blackfin adsp bf525, and I want to edit it in IDA Pro.
I tried to compile your plugin, but I'm having problems in the compiler.

you could help me?

thx, you are my last hope...

**Comment by krater** [comment]
hey !

I think I can help you, but I need some more information about your problems.

cheers,
krater

> hi krater,
> 
> i have a firmware of an blackfin adsp bf525, and I want to edit it in IDA
> Pro.
> I tried to compile your plugin, but I'm having problems in the compiler.
> 
> you could help me?
> 
> thx, you are my last hope...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/krater/Blackfin-IDA-Pro-Plugin/issues/2

---

Schuler Development - Inh. Andreas Schuler
Oberdorf 90 - 66687 Wadern - Germany
Tel.: +49 (0)176 38954028 - eMail: andreas@schulerdev.de
USt-IdNr. DE265234109

**Comment by fmgdias** [comment]
Thx man, sorry for my english, I'm from Brazil.
well, I'm working on decompiling firmware of my electronic drums (Alesis DM10)
and I've managed to decipher some sys ex files, which are based on midi, and has also managed to decipher the CRC.

But I still can not load new sounds into the module because of a lock.
And I know that the latch is in the module firmware.
I'm trying to figure out how it works these security functions of the module to be able to load new sounds.

I got the processor model also, see details bellow.
![AlesisDm10Pcb](https://f.cloud.github.com/assets/1345417/374481/a86ac01a-a39e-11e2-8f34-5c67f0ebf651.jpg)

I can send you by email the firmware?

**Comment by krater** [comment]
I think my english is not better than yours ;) I'm from germany.

It's a nice project. Is this a picture from a sound module or from the
drumcomputer itself ?

You can send me your firmware, but I don't think that I can reverse
engineer it for you. But when you say me which problems you have with
compiling my plugin, I can help you there ;)

> Thx man, sorry for my english, I'm from Brazil.
> well, I'm working on decompiling firmware of my electronic drums (Alesis
> DM10)
> and I've managed to decipher some sys ex files, which are based on midi,
> and has also managed to decipher the CRC.
> 
> But I still can not load new sounds into the module because of a lock.
> And I know that the latch is in the module firmware.
> I'm trying to figure out how it works these security functions of the
> module to be able to load new sounds.
> 
> I got the processor model also, see details bellow.
> ![AlesisDm10Pcb](https://f.cloud.github.com/assets/1345417/374481/a86ac01a-a39e-11e2-8f34-5c67f0ebf651.jpg)
> 
> I can send you by email the firmware?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/krater/Blackfin-IDA-Pro-Plugin/issues/2#issuecomment-16309366

---

Schuler Development - Inh. Andreas Schuler
Oberdorf 90 - 66687 Wadern - Germany
Tel.: +49 (0)176 38954028 - eMail: andreas@schulerdev.de
USt-IdNr. DE265234109

**Comment by fmgdias** [comment]
its drumcomputer (blackfin adsp bf525 in center-right of image) itself.

humm ... you already have the plugin compiled?
I'll send you the firmware to andreas@schulerdev.de, if you can answer me with the plugin compiled, I'll try to turn me alone.
thanks for the help, I hope it is useful.

fabricio dias
