### ISSUE TITLE
idasdk 6.8

### ISSUE THREAD

**Issue by veskohard** [krater/Blackfin-IDA-Pro-Plugin#3]
Hi
i can't buid plugin, sdk 6.8, Visual Studio 2010

1>bfin-dis.cpp(144): error C2660: 'get_colored_long_name' : function does not take 4 arguments
......
if(get_colored_long_name(pc, ea, name,60))
.....

declaration of get_colored_long_name in name.hpp:
inline ssize_t idaapi get_colored_long_name(qstring *out, ea_t ea, int gtn_flags=0)
{
  return get_ea_name(out, ea, GN_VISIBLE|GN_COLORED|GN_DEMANGLED|GN_LONG|gtn_flags);
}

**Comment by krater** [comment]
Thanks for this information. In the next months there is no spare time to fix this. Please send a fix if you have one.
